# Generated by Django 2.2.4 on 2020-12-09 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0019_auto_20190724_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='Roomtypecode',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='capacity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='typename',
            field=models.TextField(max_length=15),
        ),
    ]
