# Generated by Django 2.2.4 on 2020-12-09 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0020_auto_20201209_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='Roomtypecode',
            field=models.CharField(max_length=100),
        ),
    ]
