# Generated by Django 2.2.4 on 2020-12-10 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0021_auto_20201209_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='Roomtypecode',
            field=models.IntegerField(),
        ),
    ]
